# Generated by Django 2.1.4 on 2019-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=100, verbose_name='ChatId')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('owner', models.CharField(max_length=100, verbose_name='群主')),
                ('userlist', models.CharField(max_length=200, verbose_name='群成员')),
            ],
            options={
                'verbose_name': '微信群',
                'verbose_name_plural': '微信群',
            },
        ),
    ]
