# Generated by Django 2.1.4 on 2019-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='标识')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('ref_branch', models.CharField(max_length=100, verbose_name='关联的分支')),
            ],
            options={
                'verbose_name': 'GitLabHook',
                'verbose_name_plural': 'GitLabHook',
            },
        ),
        migrations.CreateModel(
            name='WXChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtype', models.CharField(choices=[('text', '文本消息'), ('textcard', '卡片消息'), ('markdown', 'markdown消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='文本-消息内容')),
                ('markdown_content', models.TextField(blank=True, null=True, verbose_name='Markdown-消息内容')),
                ('textcard_content', models.TextField(blank=True, null=True, verbose_name='卡片消息-消息内容')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='WXGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=100, verbose_name='ChatId')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('owner', models.CharField(max_length=100, verbose_name='群主')),
                ('userlist', models.CharField(max_length=200, verbose_name='群成员')),
            ],
            options={
                'verbose_name': '微信群',
                'verbose_name_plural': '微信群',
            },
        ),
        migrations.AddField(
            model_name='wxchatmessage',
            name='group',
            field=models.ForeignKey(on_delete=False, to='webhook.WXGroup', verbose_name='收消息的群'),
        ),
        migrations.AddField(
            model_name='gitlabhook',
            name='group',
            field=models.ForeignKey(on_delete=False, to='webhook.WXGroup', verbose_name='收消息的群'),
        ),
    ]
