# coding:utf-8
# Generated by Django 2.1.4 on 2019-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, verbose_name='hook路径')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('ref_branch', models.CharField(max_length=100, verbose_name='关联的分支')),
                ('group', models.ForeignKey(on_delete=False, to='webhook.WXGroup', verbose_name='收消息的群')),
            ],
            options={
                'verbose_name': 'GitlabHook',
                'verbose_name_plural': 'GitlabHook',
            },
        ),
    ]
