# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabhook',
            options={'verbose_name': 'GitLab Hook', 'verbose_name_plural': 'GitLab Hook'},
        ),
        migrations.AddField(
            model_name='gitlabhook',
            name='msg_title',
            field=models.CharField(default='Hook', max_length=100, verbose_name='消息标题'),
            preserve_default=False,
        ),
    ]
