# coding:utf-8
# Generated by Django 2.1.4 on 2019-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_gitlabhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtype', models.CharField(choices=[('text', '文本消息'), ('textcard', '卡片消息'), ('markdown', 'markdown消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('text_content', models.TextField(verbose_name='文本-消息内容')),
                ('markdown_content', models.TextField(verbose_name='Markdown-消息内容')),
                ('textcard_content', models.TextField(verbose_name='卡片消息-消息内容')),
                ('group', models.ForeignKey(on_delete=False, to='webhook.WXGroup', verbose_name='收消息的群')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
