# coding:utf-8
# Generated by Django 2.1.4 on 2019-01-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_auto_20190109_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxchatmessage',
            name='markdown_content',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown-消息内容'),
        ),
        migrations.AlterField(
            model_name='wxchatmessage',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='文本-消息内容'),
        ),
        migrations.AlterField(
            model_name='wxchatmessage',
            name='textcard_content',
            field=models.TextField(blank=True, null=True, verbose_name='卡片消息-消息内容'),
        ),
    ]
