# Generated by Django 2.1.4 on 2019-01-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_auto_20190109_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabhook',
            name='path',
        ),
        migrations.AddField(
            model_name='gitlabhook',
            name='key',
            field=models.CharField(default='', max_length=100, verbose_name='标识'),
            preserve_default=False,
        ),
    ]
