# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


def default_data(apps, schema_editor):
    ConfigModel = apps.get_model("config", "ConfigModel")
    db_alias = schema_editor.connection.alias
    ConfigModel.objects.using(db_alias).bulk_create([
        ConfigModel(name='站点名字', key="cfg_site_name", value="消息服务"),
        ConfigModel(name='企业微信ID', key="cfg_ewx_corp_id", value="xxx"),
        ConfigModel(name='企业微信Secret', key="cfg_ewx_corp_secret", value="xxx"),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('key', models.CharField(max_length=100, verbose_name='键')),
                ('value', models.CharField(max_length=100, verbose_name='值')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
            },
        ),
        migrations.RunPython(default_data)
    ]
